NAME = Serializer

SOURCE = main.cpp \
			Serialization.cpp

OBJECT = $(SOURCE:.cpp=.o)

HEADER = Serialization.hpp

all: $(NAME)

$(NAME): $(OBJECT) $(HEADER)
	c++ -Wall -Wextra -Werror $(OBJECT) -o $(NAME)

%.o: %.cpp
	c++ -Wall -Wextra -Werror -c $< -o $(<:.cpp=.o)

clean:
	rm -f $(OBJECT)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re